Update and add pre/post scripts; add udev rules file

diff --git a/debian/capi4hylafax.prerm b/debian/capi4hylafax.prerm
--- a/debian/capi4hylafax.prerm
+++ b/debian/capi4hylafax.prerm
@@ -1,4 +1,21 @@
-#! /bin/sh -e
+#!/bin/sh
+# prerm script for capi4hylafax
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+#
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 if [ "$1" = 'failed-upgrade' ] && dpkg --compare-versions "$2" lt '1:01.03.00.99.svn.300-14'; then
 
@@ -15,6 +32,9 @@ if [ "$1" = 'failed-upgrade' ] && dpkg --compare-versions "$2" lt '1:01.03.00.99
   fi
 
 else
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
